#!/usr/bin/env bash
# scripts/components/mcp/deploy.sh
# Runs INSIDE the mcp LXC. Idempotent. Installs 9 MCP servers as systemd services.

set -euo pipefail
: "${SOC_STATE_DIR:?}"; : "${SOC_COMPONENT:=mcp}"
: "${SOC_MCP_BIND_HOST:=127.0.0.1}"
STATE_FILE="${SOC_STATE_DIR}/state/${SOC_COMPONENT}.json"
SECRETS_DIR="${SOC_STATE_DIR}/secrets"
INSTALL_DIR="/opt/soc-mcp"
mkdir -p "${SOC_STATE_DIR}/state" "${SECRETS_DIR}" "${INSTALL_DIR}"
chmod 700 "${SECRETS_DIR}" 2>/dev/null || true

log() { printf '[mcp-deploy] %s\n' "$*"; }
write_failed() {
  jq -n --arg err "$1" '{component:"mcp",status:"failed",error:$err}' > "${STATE_FILE}"
  log "FAILED: $1"; exit 1
}
trap 'write_failed "aborted on line $LINENO"' ERR

# Server inventory: name | repo | pinned ref | port | env-key-list
# env-key-list documents what env vars integrate.sh will populate later.
# Refs are pinned commit SHAs (supply-chain: a compromised upstream repo
# cannot change what gets deployed). Bump deliberately; SHAs verified
# against each repo's main on 2026-06-10.
declare -A SERVERS=(
  [wazuh]="https://github.com/solomonneas/wazuh-mcp.git|c88fbbb5dc5afc3112c0bf28af8fefd3c98ae3a5|3001|WAZUH_URL,WAZUH_USER,WAZUH_PASSWORD"
  [thehive]="https://github.com/solomonneas/thehive-mcp.git|800a064bd5a5f4a30791185b89b50b6d9a0604a5|3002|THEHIVE_URL,THEHIVE_API_KEY"
  [cortex]="https://github.com/solomonneas/cortex-mcp.git|a8e707d58b260c976eff562aade655f060347da4|3003|CORTEX_URL,CORTEX_API_KEY"
  [misp]="https://github.com/solomonneas/misp-mcp.git|0177f296d1b3078fcfdcec31e19e5291c939a32e|3004|MISP_URL,MISP_API_KEY"
  [zeek]="https://github.com/solomonneas/zeek-mcp.git|b14c6480b3a62b7fd89c7daf55eb15f7a83aeca2|3005|ZEEK_LOG_DIR,ZEEK_LOG_FORMAT"
  [suricata]="https://github.com/solomonneas/suricata-mcp.git|ab560c00af148ebda51b050515b6a79adec2e7e6|3006|SURICATA_EVE_PATH"
  [mitre]="https://github.com/solomonneas/mitre-mcp.git|57d9044a4883d0e9bf3c126247ed930986144253|3007|MITRE_DATA_DIR"
  [rapid7]="https://github.com/solomonneas/rapid7-mcp.git|a89e2da394bc7fd5cf44af2997a3b93de53b66bf|3008|RAPID7_URL,RAPID7_API_KEY"
  [sophos]="https://github.com/solomonneas/sophos-mcp.git|90bc28aa34a424d904a4aa9e91cd367809f2740f|3009|SOPHOS_CLIENT_ID,SOPHOS_CLIENT_SECRET"
)

# Idempotency: every systemd unit active?
all_active=1
for name in "${!SERVERS[@]}"; do
  if ! systemctl is-active --quiet "soc-mcp-${name}" 2>/dev/null; then
    all_active=0; break
  fi
done

export DEBIAN_FRONTEND=noninteractive

if [[ "${all_active}" -eq 0 ]]; then
  log "installing deps"
  apt-get update -qq
  apt-get install -y -qq curl git ca-certificates jq openssl python3-pip python3-venv nginx

  # Wait for DNS + connectivity (LXC may not be fully online yet)
  for _ in $(seq 1 30); do
    if curl -sf --max-time 3 https://github.com/ >/dev/null 2>&1; then break; fi
    sleep 2
  done

  if ! command -v node >/dev/null 2>&1 || (( "$(node -v | sed 's/[v.]/ /g' | awk '{print $1}')" < 20 )); then
    log "installing Node.js 20"
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y -qq nodejs
  fi

  # Install mcp-proxy: bridges stdio MCP servers to SSE endpoints.
  # The 9 MCP server repos use stdio transport (the primary MCP transport,
  # what Claude Desktop uses directly). mcp-proxy wraps each as an SSE endpoint
  # so remote MCP clients can connect over HTTP.
  if [[ ! -x /usr/local/bin/mcp-proxy ]]; then
    log "installing mcp-proxy (stdio <-> SSE bridge) into /opt/mcp-proxy venv"
    python3 -m venv /opt/mcp-proxy
    /opt/mcp-proxy/bin/pip install --quiet --upgrade pip
    /opt/mcp-proxy/bin/pip install --quiet mcp-proxy
    ln -sf /opt/mcp-proxy/bin/mcp-proxy /usr/local/bin/mcp-proxy
  fi
fi

IP="$(hostname -I | awk '{print $1}')"
ENDPOINT_HOST="${SOC_MCP_BIND_HOST}"
if [[ "${ENDPOINT_HOST}" == "0.0.0.0" || "${ENDPOINT_HOST}" == "::" ]]; then
  ENDPOINT_HOST="${IP}"
fi
ENDPOINTS_JSON='[]'

# mcp-proxy has no server-side auth of its own, so the advertised bearer token
# was previously never enforced: the SSE endpoints accepted any request. We put
# nginx in front as an authenticating reverse proxy - mcp-proxy binds loopback
# on an internal port, nginx owns the public port and rejects any request whose
# Authorization header is not the exact bearer token. Server blocks accumulate
# here and are written after the loop.
NGINX_CONF="# soc-stack MCP auth gateway - generated by mcp/deploy.sh. Do not edit.\n"

for name in wazuh thehive cortex misp zeek suricata mitre rapid7 sophos; do
  IFS='|' read -r repo ref port env_keys <<< "${SERVERS[$name]}"
  dest="${INSTALL_DIR}/${name}-mcp"
  # mcp-proxy listens here on loopback; nginx listens on the public ${port}.
  internal_port=$(( port + 10000 ))

  # Token: persisted on first install, reused on idempotent re-runs
  token_file="${SECRETS_DIR}/mcp-${name}-token.txt"
  if [[ -f "${token_file}" ]]; then
    token="$(cat "${token_file}")"
  else
    token="$(openssl rand -hex 20)"
    printf '%s' "${token}" > "${token_file}"
    chmod 600 "${token_file}"
  fi

  # Clone or update repo, then check out the pinned ref
  if [[ -d "${dest}/.git" ]]; then
    git -C "${dest}" fetch --quiet origin || true
  else
    # Retry git clone up to 3 times
    clone_ok=0
    for attempt in 1 2 3; do
      if git clone --quiet "${repo}" "${dest}"; then
        clone_ok=1; break
      fi
      log "clone attempt ${attempt}/3 failed for ${repo}, retrying in 5s"
      sleep 5
      rm -rf "${dest}"
    done
    [[ "${clone_ok}" -eq 1 ]] || write_failed "git clone failed for ${repo} after 3 attempts"
  fi
  git -C "${dest}" checkout --quiet --detach "${ref}" \
    || write_failed "pinned ref ${ref} not found in ${repo}"
  ( cd "${dest}" && npm install --silent && (npm run build --silent 2>/dev/null || true) )

  # systemd unit + env file
  env_file="/etc/soc-mcp/${name}.env"
  mkdir -p /etc/soc-mcp
  if [[ ! -f "${env_file}" ]]; then
    {
      echo "# Populated by integrate.sh after peer components come up."
      echo "PORT=${port}"
      echo "MCP_BEARER_TOKEN=${token}"
      echo "MCP_TRANSPORT=sse"
      # placeholders for the per-server env keys
      IFS=',' read -r -a keys <<< "${env_keys}"
      for k in "${keys[@]}"; do
        echo "${k}="
      done
    } > "${env_file}"
    chmod 600 "${env_file}"
  fi

  unit="/etc/systemd/system/soc-mcp-${name}.service"
  cat > "${unit}" <<UEOF
[Unit]
Description=SOC MCP server: ${name} (stdio wrapped as SSE via mcp-proxy)
After=network.target

[Service]
Type=simple
EnvironmentFile=${env_file}
WorkingDirectory=${dest}
ExecStart=/usr/local/bin/mcp-proxy --sse-port ${internal_port} --sse-host 127.0.0.1 -- /usr/bin/node dist/index.js
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectKernelTunables=true
ProtectControlGroups=true

[Install]
WantedBy=multi-user.target
UEOF

  systemctl daemon-reload
  systemctl enable --now "soc-mcp-${name}.service" >/dev/null 2>&1 || true

  ENDPOINTS_JSON="$(jq --arg n "${name}" --arg url "http://${ENDPOINT_HOST}:${port}/sse" --arg tok "${token}" \
    '. + [{name:$n, url:$url, token:$tok}]' <<< "${ENDPOINTS_JSON}")"

  # nginx server block: require the exact bearer token, then proxy to the
  # loopback mcp-proxy. SSE needs buffering off, HTTP/1.1, and long read timeout.
  NGINX_CONF+="server {\n"
  NGINX_CONF+="    listen ${SOC_MCP_BIND_HOST}:${port};\n"
  NGINX_CONF+="    server_name _;\n"
  NGINX_CONF+="    location / {\n"
  NGINX_CONF+="        if (\$http_authorization != \"Bearer ${token}\") { return 401; }\n"
  NGINX_CONF+="        proxy_pass http://127.0.0.1:${internal_port};\n"
  NGINX_CONF+="        proxy_http_version 1.1;\n"
  NGINX_CONF+="        proxy_set_header Host \$host;\n"
  NGINX_CONF+="        proxy_set_header Connection \"\";\n"
  NGINX_CONF+="        proxy_buffering off;\n"
  NGINX_CONF+="        proxy_cache off;\n"
  NGINX_CONF+="        proxy_read_timeout 3600s;\n"
  NGINX_CONF+="        chunked_transfer_encoding off;\n"
  NGINX_CONF+="    }\n"
  NGINX_CONF+="}\n"
done

# Write the combined auth gateway, validate, and (re)load nginx. A bad config
# must not take the whole component down silently, so `nginx -t` gates the reload.
printf '%b' "${NGINX_CONF}" > /etc/nginx/conf.d/soc-mcp.conf
if ! nginx -t >/dev/null 2>&1; then
  write_failed "generated nginx auth-gateway config failed validation (nginx -t)"
fi
systemctl enable --now nginx >/dev/null 2>&1 || true
systemctl reload nginx || systemctl restart nginx

jq -n \
  --arg ip "${IP}" \
  --arg bind_host "${SOC_MCP_BIND_HOST}" \
  --argjson eps "${ENDPOINTS_JSON}" \
  '{
    component: "mcp",
    status: "deployed",
    host_ip: $ip,
    bind_host: $bind_host,
    mcp_endpoints: $eps,
    services: ($eps | map("soc-mcp-" + .name))
  }' > "${STATE_FILE}"

log "deployed ${#SERVERS[@]} MCP servers"
trap - ERR
